// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="../types/index.d.ts" />

import { setErrorLogger } from "luna-base-utils";
import "./buffers/f32array";
import "./buffers/i16array";
import "./buffers/i32array";
import "./buffers/i8array";
import "./buffers/native_array";
import "./buffers/pointer_array";
import "./buffers/u16array";
import "./buffers/u8array";
import "./gl/gl_buffer";
import "./gl/gl_geometry_buffer";
import "./gl/gl_program";
import "./gl/gl_texture";
import "./gl/gl_vertex_array";
import "./gl_renderer/basic_shader_program";
import "./gl_renderer/geometry";
import "./gl_renderer/gl_renderer";
import "./gl_renderer/image";
import "./gl_renderer/material";
import "./gl_renderer/primitives";
import "./gl_renderer/shader";
import "./gl_renderer/shader_program";
import "./gl_renderer/sub_mesh";
import "./gl_renderer/tasks/application_event";
import "./gl_renderer/tasks/application_task";
import "./gl_renderer/tasks/gl_renderer_task";
import "./gl_renderer/tasks/image_task";
import "./gl_renderer/tasks/imgui_render_nodes_task";
import "./gl_renderer/tasks/input_task";
import "./gl_renderer/tasks/material_task";
import "./gl_renderer/tasks/node_task";
import "./gl_renderer/tasks/null_task";
import "./gl_renderer/tasks/shader_program_task";
import "./gl_renderer/tasks/shader_task";
import "./gl_renderer/tasks/sub_mesh_task";
import "./gl_renderer/tasks/vec4_task";
import "./gl_renderer/texture";
import "./gl_renderer/transforms/basic_transform";
import "./gl_renderer/transforms/ortho_camera_transform";
import "./gl_renderer/transforms/perspective_camera_transform";
import "./gl_renderer/transforms/transform";
import "./images/png_image";
import { logger } from "./logger";
import "./math/mat4";
import "./math/math_common";
import "./math/vec3";
import "./op_utils";
import "./platform";
import "./tables";
import "./tprint";
import "./type_utils";
import "./uuid";
setErrorLogger(function (this: void, msg: string) {
  logger.error("%s", msg);
});
